version: '2'
services:  
  app:        
    restart: always
    image: lincolnbrito/app
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - ${APP_DIR}/:/var/www/html
     - ${COMPOSER_CACHE_DIR}:${COMPOSER_CACHE_DIR_CONTAINER}
    ports:
     - "${APP_PORT}:80"    
    networks:
     - sdnet 
networks:
  sdnet:
    driver: "bridge"